- .github/workflows/dependency-graph.yml
> 🤖 ci: Add dependency graph workflow

- modules/docs/src/docs/.asciidoctorconfig
- modules/docs/src/docs/user-guide/30_modules/30_flags.adoc
- modules/docs/src/site/templates/header.gsp
- modules/example/src/main/scala/example/app.scala
- modules/flags/src/main/scala/pillars/flags/package.scala
- project/Dependencies.scala
> ✨ feat(flags): Add string interpolator for feature flag name

- .scala-steward.conf
- build.sbt
- modules/core/src/main/scala/pillars/app.scala
- modules/docs/src/docs/user-guide/30_modules/30_flags.adoc
- modules/example/src/main/scala/example/app.scala
- modules/flags/src/main/scala/pillars/flags/FlagManager.scala
- modules/flags/src/main/scala/pillars/flags/package.scala
- modules/flags/src/test/scala/pillars/flags/FeatureFlagTests.scala
- modules/flags/src/test/scala/pillars/flags/FlagManagerTests.scala
- project/Dependencies.scala
whenEnabled can now be called directly on FeatureFlag.Name
> ✨ feat(flags): Better DX for flags

- .scalafix.conf
- build.sbt
- modules/core/src/main/scala/pillars/Observability.scala
- modules/core/src/main/scala/pillars/app.scala
- modules/db/src/main/scala/pillars/db/db.scala
- modules/docs/src/docs/user-guide/10_quick-start.adoc
- modules/docs/src/docs/user-guide/index.adoc
- modules/example/src/main/resources/config.yaml
- modules/example/src/main/scala/example/app.scala
- modules/flags/src/main/scala/pillars/flags/FlagManager.scala
- project/plugins.sbt
> 🔨 refactor(core): Introduce AppInfo to ease app declaration

- modules/core/src/main/scala/pillars/AdminServer.scala
- modules/core/src/main/scala/pillars/ApiServer.scala
- modules/core/src/main/scala/pillars/HttpServer.scala
- modules/core/src/main/scala/pillars/Observability.scala
- modules/core/src/main/scala/pillars/config.scala
- modules/db/src/main/scala/pillars/db/db.scala
- modules/docs/src/docs/user-guide/20_features/10_configuration.adoc
- modules/example/src/main/resources/config.yaml
> 📚 docs(core): 31 Add documentation for configuration

- .better-commits.json
- modules/docs/src/docs/user-guide/20_features/10_configuration.adoc
- modules/docs/src/docs/user-guide/20_features/20_logging.adoc
> 📚 docs(core): #32 Add documentation for logging

- modules/core/src/main/scala/pillars/app.scala
- modules/docs/src/docs/user-guide/20_features/60_admin-server.adoc
- modules/docs/src/docs/user-guide/30_modules/30_flags.adoc
> 📚 docs(core): #34 Add documentation for admin server

- modules/core/src/main/scala/pillars/probes.scala
- modules/docs/src/docs/user-guide/20_features/30_probes.adoc
> 📚 docs(core): #47 Add documentation for probes

- .github/workflows/release.yml
- build.sbt
- project/plugins.sbt
> 🚧 build: Add publishing to sonatype

- build.sbt
> 🚧 build: Fix homepage for publishing

- .better-commits.json
- .github/workflows/release.yml
> build: Create release automatically

- .github/workflows/release.yml
- docToolchainConfig.groovy
- modules/docs/src/docs/.asciidoctorconfig
- modules/docs/src/docs/user-guide/10_quick-start.adoc
- modules/docs/src/site/doc/landingpage.gsp
> docs: Automatically update version in docs when releasing

- modules/docs/src/site/doc/landingpage.gsp
> docs: Fix code in homepage

- modules/core/src/main/scala/pillars/Pillars.scala
- modules/core/src/main/scala/pillars/modules.scala
- modules/db/src/main/scala/pillars/db/db.scala
- modules/example/src/main/rest/admin.http
- modules/flags/src/main/scala/pillars/flags/FlagManager.scala
- modules/flags/src/main/scala/pillars/flags/package.scala
- modules/http-client/src/main/scala/pillars/httpclient/httpclient.scala
- [] I have added tests to cover my changes.
> refactor(core): Remove usage of reflection for modules

- modules/docs/src/site/doc/landingpage.gsp
> fix(docs): #61 Reflect usage of context function in home page

- modules/core/src/main/scala/pillars/Config.scala
- modules/core/src/main/scala/pillars/Logging.scala
- modules/core/src/main/scala/pillars/Pillars.scala
- modules/core/src/main/scala/pillars/app.scala
- modules/core/src/main/scala/pillars/codec.scala
- modules/db/src/main/scala/pillars/db/db.scala
- modules/flags/src/main/scala/pillars/flags/FlagManager.scala
> refactor(core): #64 Use fs2 Path instead of java.nio

- .better-commits.json
- modules/db-migration/src/test/resources/db/migrations/V001__init.sql
- modules/db-migration/src/test/resources/db/migrations/V002__update.sql
- modules/db-migration/src/test/scala/pillars/db/migration/MigrationTests.scala
- project/Dependencies.scala
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
> test(db-migration): Add tests for DB migrations

- modules/core/src/main/scala/pillars/app.scala
- modules/core/src/main/scala/pillars/commands.scala
- modules/core/src/main/scala/pillars/openapi.scala
- modules/core/src/main/scala/pillars/package.scala
- modules/example/src/main/scala/example/app.scala
- project/Dependencies.scala
- project/plugins.sbt
> feat: Add OpenAPI generation

- modules/db-doobie/src/main/resources/META-INF/services/pillars.Loader
> Add doobie loader

- build.sbt
- modules/redis-rediculous/src/main/resources/META-INF/services/pillars.Loader
- modules/redis-rediculous/src/main/scala/pillars/redis_rediculous/redis.scala
- project/Dependencies.scala
Added a Rediculous redis module based on the lib : https://github.com/davenverse/rediculous
- [not] I have read the **CONTRIBUTING** document.
- [hopefuly] My code follows the code style of this project.
- [I guess...] My change requires a change to the documentation.
- [nope] I have updated the documentation accordingly.
- [you bet] I have added tests to cover my changes.
- [this PR will tell] All new and existing tests passed.
> Add rediculous redis module

- modules/core/src/main/scala/pillars/Observability.scala
> fix(core): Make Observability usable

- .gitignore
- modules/docs/src/docs/user-guide/30_modules/40_redis.adoc
- modules/docs/src/docs/user-guide/30_modules/41_rabbitmq.adoc
- modules/docs/src/docs/user-guide/30_modules/index.adoc
- modules/rabbitmq-fs2/src/test/scala/pillars/rabbitmq/fs2/RabbitMQTests.scala
(Basic) doc for RabbitMQ module.
Also:
- add skeleton for Redis module doc
- fix dead code in RabbitMQ tests
> doc: document RabbitMQ module

- build.sbt
- project/Dependencies.scala
> chore: Upgrade otel4s to 0.8.0 and skunk to 1.0.0-M7

- modules/core/src/main/scala/pillars/AdminServer.scala
- modules/core/src/main/scala/pillars/ApiServer.scala
- modules/core/src/main/scala/pillars/HttpServer.scala
- modules/core/src/main/scala/pillars/Pillars.scala
- modules/docs/src/docs/user-guide/20_features/10_configuration.adoc
- modules/example/src/main/resources/config.yaml
- project/Dependencies.scala
Closes: #129
Depending on the configuration, Swagger UI is added to api and admin servers
#129 
Nothing special
> feat(core): #129 Include OpenAPI documentation on HTTP servers

- modules/core/src/main/scala/pillars/codec.scala
- modules/db-skunk/src/main/scala/pillars/db/db.scala
Documentation will be updated in a following PR
> feat(db-skunk): Allow session configuration

- docToolchainConfig.groovy
- modules/docs/src/docs/user-guide/index.adoc
> fix(docs): Fix project name replacement in overview

- modules/core/src/main/scala/pillars/AdminServer.scala
- modules/core/src/main/scala/pillars/ApiServer.scala
- modules/core/src/main/scala/pillars/Config.scala
- modules/core/src/main/scala/pillars/HttpServer.scala
- modules/core/src/main/scala/pillars/Logging.scala
- modules/core/src/main/scala/pillars/Observability.scala
- modules/core/src/main/scala/pillars/modules.scala
- modules/core/src/main/scala/pillars/probes.scala
- modules/db-doobie/src/main/scala/pillars/db_doobie/db.scala
- modules/db-migration/src/main/scala/pillars/db/migrations/migrations.scala
- modules/db-skunk/src/main/scala/pillars/db/db.scala
- modules/flags/src/main/scala/pillars/flags/FlagManager.scala
- modules/flags/src/main/scala/pillars/flags/FlagsConfig.scala
- modules/http-client/src/main/scala/pillars/httpclient/httpclient.scala
- modules/http-client/src/test/scala/pillars/httpclient/HttpClientSuite.scala
- modules/rabbitmq-fs2/src/main/scala/pillars/rabbitmq/fs2/rabbitmq.scala
- modules/redis-rediculous/src/main/scala/pillars/redis_rediculous/redis.scala
> feat: #159 Expose config of optional modules

- modules/core/src/main/scala/pillars/Observability.scala
- modules/core/src/main/scala/pillars/Pillars.scala
- modules/docs/src/docs/user-guide/30_modules/20_http-client.adoc
avoid summon[Pillars[F]] and use Pillars[F] instead
> style: added apply method for Pillars[F]
